# Generated by Django 4.1 on 2022-08-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('nombres', models.CharField(blank=True, max_length=15, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=15, null=True)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Usuario')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Em@il')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_estudiante', models.BooleanField(default=False)),
                ('is_docente', models.BooleanField(default=False)),
                ('is_gestor', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_coordinador', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at', '-updated_at'),
            },
        ),
    ]
