# Generated by Django 4.1 on 2022-08-30 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=15, unique=True)),
                ('an_creacion', models.CharField(default=datetime.datetime.now, max_length=50)),
            ],
        ),
    ]
