# Generated by Django 4.1 on 2022-09-06 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_periodos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_prog', models.CharField(max_length=10, unique=True, verbose_name='Código del Programa')),
                ('programa_name', models.CharField(max_length=100, verbose_name='Nombre del Programa')),
                ('aceptado', models.PositiveIntegerField(verbose_name='Total materias para grado')),
                ('an_creacion', models.CharField(default=datetime.datetime.now, max_length=50)),
                ('is_primaria', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_bachiller', models.BooleanField(default=False)),
                ('is_tecnico', models.BooleanField(default=False)),
                ('is_tecnologo', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='periodos',
            options={'ordering': ('-an_creacion',)},
        ),
    ]
