# Generated by Django 4.1 on 2022-09-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_docente_estudiante_inventario_pensum_materias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apellidos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombres',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
