# Generated by Django 4.1 on 2022-09-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_alter_user_apellidos_alter_user_nombres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materias',
            name='codigo',
            field=models.PositiveIntegerField(verbose_name='Código'),
        ),
    ]
