# Generated by Django 4.1 on 2022-09-28 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_alter_materias_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduated',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha'),
        ),
    ]
