# Generated by Django 4.1 on 2022-09-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_graduated_fecha_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='masivo',
            field=models.BooleanField(default=True),
        ),
    ]
