# Generated by Django 4.1 on 2022-10-19 23:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0008_estudiante_masivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C1', models.BooleanField(default=False)),
                ('C2', models.BooleanField(default=False)),
                ('C3', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='masivo',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Acciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('accion', models.CharField(max_length=100, verbose_name='accion')),
                ('fecha_reg', models.DateField(default=datetime.datetime.now, verbose_name='Fecha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
