# Generated by Django 4.1 on 2022-10-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_habilitaciones_cerrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciones',
            name='corte',
            field=models.CharField(default=False, max_length=100, verbose_name='Nombres'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acciones',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habilitaciones',
            name='B1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habilitaciones',
            name='B2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habilitaciones',
            name='B3',
            field=models.BooleanField(default=False),
        ),
    ]
