# Generated by Django 4.1 on 2022-10-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0011_acciones_corte_acciones_estado_habilitaciones_b1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilitaciones',
            name='CF',
            field=models.BooleanField(default=False),
        ),
    ]
