# Generated by Django 4.1 on 2022-10-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0013_remove_acciones_corte_remove_acciones_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciones',
            name='usuario',
            field=models.CharField(max_length=100, verbose_name='Usuario'),
        ),
    ]
