# Generated by Django 4.1 on 2022-10-24 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0014_alter_acciones_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acciones',
            options={'ordering': ['-fecha_reg']},
        ),
    ]
