# Generated by Django 4.1 on 2022-11-18 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0015_alter_acciones_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acciones',
            options={},
        ),
    ]
