# Generated by Django 4.1 on 2023-01-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0016_alter_acciones_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='programas',
            name='costo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=25),
        ),
    ]
