# Generated by Django 4.1 on 2023-01-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0018_programas_cuota_valor_programas_cuotas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programas',
            name='is_curso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programas',
            name='is_diplomado',
            field=models.BooleanField(default=False),
        ),
    ]
