# Generated by Django 4.1 on 2023-01-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0019_programas_is_curso_programas_is_diplomado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogsTypesGen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogsTypesProg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogsTypesRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=200)),
            ],
        ),
    ]
