# Generated by Django 4.1 on 2023-01-11 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0020_catalogstypesgen_catalogstypesprog_catalogstypesrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='programas',
            name='tipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academico.catalogstypesprog'),
            preserve_default=False,
        ),
    ]
