# Generated by Django 4.1 on 2023-01-11 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0021_programas_tipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programas',
            name='is_bachiller',
        ),
        migrations.RemoveField(
            model_name='programas',
            name='is_curso',
        ),
        migrations.RemoveField(
            model_name='programas',
            name='is_diplomado',
        ),
        migrations.RemoveField(
            model_name='programas',
            name='is_primaria',
        ),
        migrations.RemoveField(
            model_name='programas',
            name='is_tecnico',
        ),
        migrations.RemoveField(
            model_name='programas',
            name='is_tecnologo',
        ),
    ]
