# Generated by Django 4.1 on 2023-01-16 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0023_remove_user_is_admin_remove_user_is_coordinador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='costo_cierre',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='acciones',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 1, 16, 18, 36, 59, 775108), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 1, 16, 18, 36, 59, 772108), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 1, 16, 18, 36, 59, 773108), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='graduated',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 1, 16, 18, 36, 59, 774110), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 1, 16, 18, 36, 59, 771110), max_length=50),
        ),
        migrations.AlterField(
            model_name='materias',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 1, 16, 18, 36, 59, 772108), max_length=50),
        ),
        migrations.AlterField(
            model_name='pensum',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 1, 16, 18, 36, 59, 771110), max_length=50),
        ),
        migrations.AlterField(
            model_name='periodos',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 1, 16, 18, 36, 59, 770111), max_length=50),
        ),
        migrations.AlterField(
            model_name='programas',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 1, 16, 18, 36, 59, 770111), max_length=50),
        ),
    ]
