# Generated by Django 4.1 on 2023-01-18 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0028_alter_acciones_fecha_reg_alter_docente_fecha_reg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogsSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='acciones',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 1, 18, 22, 52, 12, 598952), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 1, 18, 22, 52, 12, 595953), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 1, 18, 22, 52, 12, 596952), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='graduated',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 1, 18, 22, 52, 12, 598952), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 1, 18, 22, 52, 12, 595953), max_length=50),
        ),
        migrations.AlterField(
            model_name='materias',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 1, 18, 22, 52, 12, 596952), max_length=50),
        ),
        migrations.AlterField(
            model_name='pensum',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 1, 18, 22, 52, 12, 594952), max_length=50),
        ),
        migrations.AlterField(
            model_name='periodos',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 1, 18, 22, 52, 12, 594952), max_length=50),
        ),
        migrations.AlterField(
            model_name='programas',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 1, 18, 22, 52, 12, 594952), max_length=50),
        ),
    ]
