# Generated by Django 4.1 on 2023-02-16 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0037_alter_acciones_fecha_reg_alter_docente_fecha_reg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciones',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 2, 16, 16, 22, 31, 663215), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 2, 16, 16, 22, 31, 660215), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 2, 16, 16, 22, 31, 661216), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='graduated',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 2, 16, 16, 22, 31, 662215), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 2, 16, 16, 22, 31, 660215), max_length=50),
        ),
        migrations.AlterField(
            model_name='materias',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 2, 16, 16, 22, 31, 661216), max_length=50),
        ),
        migrations.AlterField(
            model_name='pensum',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 2, 16, 16, 22, 31, 659216), max_length=50),
        ),
        migrations.AlterField(
            model_name='periodos',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 2, 16, 16, 22, 31, 658222), max_length=50),
        ),
        migrations.AlterField(
            model_name='programas',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 2, 16, 16, 22, 31, 659216), max_length=50),
        ),
    ]
