# Generated by Django 4.1 on 2023-08-03 00:30

import Applications.academico.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0038_alter_acciones_fecha_reg_alter_docente_fecha_reg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogsTypesDocuement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='acciones',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 8, 3, 2, 30, 13, 359773), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, validators=[Applications.academico.validators.validate_cero], verbose_name='Número de cédula'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 8, 3, 2, 30, 13, 359773), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nacimiento',
            field=models.DateField(validators=[Applications.academico.validators.validate_nacimiento], verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otros', 'Otros')], default='Femenino', max_length=50, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='telefono',
            field=models.CharField(max_length=10, validators=[Applications.academico.validators.validate_telefono], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 8, 3, 2, 30, 13, 359773), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='graduated',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 8, 3, 2, 30, 13, 359773), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 8, 3, 2, 30, 13, 359773), max_length=50),
        ),
        migrations.AlterField(
            model_name='materias',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 8, 3, 2, 30, 13, 359773), max_length=50),
        ),
        migrations.AlterField(
            model_name='pensum',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 8, 3, 2, 30, 13, 359773), max_length=50),
        ),
        migrations.AlterField(
            model_name='periodos',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 8, 3, 2, 30, 13, 359773), max_length=50),
        ),
        migrations.AlterField(
            model_name='programas',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 8, 3, 2, 30, 13, 359773), max_length=50),
        ),
    ]
