# Generated by Django 4.1 on 2023-08-03 00:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0039_catalogstypesdocuement_alter_acciones_fecha_reg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='tDocument',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academico.catalogstypesdocuement', verbose_name='Tipo de documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acciones',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 8, 3, 2, 40, 5, 686339), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 8, 3, 2, 40, 5, 686339), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 8, 3, 2, 40, 5, 686339), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='graduated',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 8, 3, 2, 40, 5, 686339), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 8, 3, 2, 40, 5, 686339), max_length=50),
        ),
        migrations.AlterField(
            model_name='materias',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 8, 3, 2, 40, 5, 686339), max_length=50),
        ),
        migrations.AlterField(
            model_name='pensum',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 8, 3, 2, 40, 5, 686339), max_length=50),
        ),
        migrations.AlterField(
            model_name='periodos',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 8, 3, 2, 40, 5, 686339), max_length=50),
        ),
        migrations.AlterField(
            model_name='programas',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 8, 3, 2, 40, 5, 686339), max_length=50),
        ),
    ]
