# Generated by Django 4.1 on 2023-08-10 10:07

import Applications.academico.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0042_alter_acciones_fecha_reg_alter_docente_fecha_reg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciones',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 8, 10, 12, 6, 59, 486764), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='corte1',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[Applications.academico.validators.validate_decimal], verbose_name='corte 1'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='corte2',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[Applications.academico.validators.validate_decimal], verbose_name='corte 2'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='corte3',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[Applications.academico.validators.validate_decimal], verbose_name='corte 3'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 8, 10, 12, 6, 59, 482242), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[Applications.academico.validators.validate_blanco], verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 8, 10, 12, 6, 59, 483242), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='graduated',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 8, 10, 12, 6, 59, 485754), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 8, 10, 12, 6, 59, 482242), max_length=50),
        ),
        migrations.AlterField(
            model_name='materias',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 8, 10, 12, 6, 59, 483242), max_length=50),
        ),
        migrations.AlterField(
            model_name='pensum',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 8, 10, 12, 6, 59, 481243), max_length=50),
        ),
        migrations.AlterField(
            model_name='periodos',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 8, 10, 12, 6, 59, 481243), max_length=50),
        ),
        migrations.AlterField(
            model_name='programas',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 8, 10, 12, 6, 59, 481243), max_length=50),
        ),
    ]
