# Generated by Django 4.1 on 2023-08-17 14:45

import Applications.academico.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0044_estudiante_tdocument_alter_acciones_fecha_reg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='acciones',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 8, 17, 16, 45, 35, 186268), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 8, 17, 16, 45, 35, 182219), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cedula',
            field=models.CharField(max_length=20, validators=[Applications.academico.validators.validate_cero], verbose_name='Identificación del Estudiante'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cedula_acudiente',
            field=models.CharField(max_length=20, validators=[Applications.academico.validators.validate_cero], verbose_name='Cédula del acudiente'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 8, 17, 16, 45, 35, 184219), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nacimiento',
            field=models.DateField(validators=[Applications.academico.validators.clean_nacimiento2], verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='pensum_asig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.pensum', verbose_name='pensum_asig'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(max_length=10, validators=[Applications.academico.validators.validate_telefono], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono_acudiente',
            field=models.CharField(max_length=10, validators=[Applications.academico.validators.validate_telefono], verbose_name='Teléfono del acudiente'),
        ),
        migrations.AlterField(
            model_name='graduated',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 8, 17, 16, 45, 35, 185218), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 8, 17, 16, 45, 35, 182219), max_length=50),
        ),
        migrations.AlterField(
            model_name='materias',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 8, 17, 16, 45, 35, 183223), max_length=50),
        ),
        migrations.AlterField(
            model_name='pensum',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 8, 17, 16, 45, 35, 181219), max_length=50),
        ),
        migrations.AlterField(
            model_name='periodos',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 8, 17, 16, 45, 35, 180222), max_length=50),
        ),
        migrations.AlterField(
            model_name='programas',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 8, 17, 16, 45, 35, 181219), max_length=50),
        ),
    ]
