# Generated by Django 4.1 on 2023-08-26 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0046_alter_acciones_fecha_reg_alter_docente_fecha_reg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='A1',
            new_name='cerrado',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='A2',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='A3',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='B1',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='B2',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='B3',
        ),
        migrations.AlterField(
            model_name='acciones',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 8, 26, 2, 37, 24, 246098), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 8, 26, 2, 37, 24, 242098), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 8, 26, 2, 37, 24, 243099), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='graduated',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 8, 26, 2, 37, 24, 244098), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 8, 26, 2, 37, 24, 241099), max_length=50),
        ),
        migrations.AlterField(
            model_name='materias',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 8, 26, 2, 37, 24, 242098), max_length=50),
        ),
        migrations.AlterField(
            model_name='pensum',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 8, 26, 2, 37, 24, 241099), max_length=50),
        ),
        migrations.AlterField(
            model_name='periodos',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 8, 26, 2, 37, 24, 240099), max_length=50),
        ),
        migrations.AlterField(
            model_name='programas',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 8, 26, 2, 37, 24, 241099), max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 2, 37, 24, 240099)),
        ),
    ]
