# Generated by Django 4.1 on 2023-11-09 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0048_remove_banner_cerrado_alter_acciones_fecha_reg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='nacionalidad',
            field=models.CharField(choices=[('Afghanistan', 'Afghanistan'), ('Albania', 'Albania'), ('Algeria', 'Algeria'), ('American\xa0Samoa', 'American\xa0Samoa'), ('Andorra', 'Andorra'), ('Angola', 'Angola'), ('Anguilla', 'Anguilla'), ('Antarctica', 'Antarctica'), ('Antigua\xa0&\xa0Barbuda', 'Antigua\xa0&\xa0Barbuda'), ('Argentina', 'Argentina'), ('Armenia', 'Armenia'), ('Aruba', 'Aruba'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Azerbaijan', 'Azerbaijan'), ('Bahama', 'Bahama'), ('Bahrain', 'Bahrain'), ('Bangladesh', 'Bangladesh'), ('Barbados', 'Barbados'), ('Belarus', 'Belarus'), ('Belgium', 'Belgium'), ('Belize', 'Belize'), ('Benin', 'Benin'), ('Bermuda', 'Bermuda'), ('Bhutan', 'Bhutan'), ('Bolivia', 'Bolivia'), ('Bosnia\xa0and\xa0Herzegovina', 'Bosnia\xa0and\xa0Herzegovina'), ('Botswana', 'Botswana'), ('Bouvet\xa0Island', 'Bouvet\xa0Island'), ('Brazil', 'Brazil'), ('British\xa0Indian\xa0Ocean\xa0Territory', 'British\xa0Indian\xa0Ocean\xa0Territory'), ('British\xa0Virgin\xa0Islands', 'British\xa0Virgin\xa0Islands'), ('Brunei\xa0Darussalam', 'Brunei\xa0Darussalam'), ('Bulgaria', 'Bulgaria'), ('Burkina\xa0Faso', 'Burkina\xa0Faso'), ('Burundi', 'Burundi'), ('Cambodia', 'Cambodia'), ('Cameroon', 'Cameroon'), ('Canada', 'Canada'), ('Cape\xa0Verde', 'Cape\xa0Verde'), ('Cayman\xa0Islands', 'Cayman\xa0Islands'), ('Central\xa0African\xa0Republic', 'Central\xa0African\xa0Republic'), ('Chad', 'Chad'), ('Chile', 'Chile'), ('China', 'China'), ('Christmas\xa0Island', 'Christmas\xa0Island'), ('Cocos\xa0\xa0Keeling\xa0Islands', 'Cocos\xa0\xa0Keeling\xa0Islands'), ('Colombia', 'Colombia'), ('Comoros', 'Comoros'), ('Congo', 'Congo'), ('Cook\xa0Iislands', 'Cook\xa0Iislands'), ('Costa\xa0Rica', 'Costa\xa0Rica'), ('Croatia', 'Croatia'), ('Cuba', 'Cuba'), ('Cyprus', 'Cyprus'), ('Czech\xa0Republic', 'Czech\xa0Republic'), ('Denmark', 'Denmark'), ('Djibouti', 'Djibouti'), ('Dominica', 'Dominica'), ('Dominican\xa0Republic', 'Dominican\xa0Republic'), ('East\xa0Timor', 'East\xa0Timor'), ('Ecuador', 'Ecuador'), ('Egypt', 'Egypt'), ('El\xa0Salvador', 'El\xa0Salvador'), ('Equatorial\xa0Guinea', 'Equatorial\xa0Guinea'), ('Eritrea', 'Eritrea'), ('Estonia', 'Estonia'), ('Ethiopia', 'Ethiopia'), ('Falkland\xa0Islands\xa0\xa0Malvinas', 'Falkland\xa0Islands\xa0\xa0Malvinas'), ('Faroe\xa0Islands', 'Faroe\xa0Islands'), ('Fiji', 'Fiji'), ('Finland', 'Finland'), ('France', 'France'), ('France', 'France'), ('French\xa0Guiana', 'French\xa0Guiana'), ('French\xa0Polynesia', 'French\xa0Polynesia'), ('French\xa0Southern\xa0Territories', 'French\xa0Southern\xa0Territories'), ('Gabon', 'Gabon'), ('Gambia', 'Gambia'), ('Georgia', 'Georgia'), ('Germany', 'Germany'), ('Ghana', 'Ghana'), ('Gibraltar', 'Gibraltar'), ('Greece', 'Greece'), ('Greenland', 'Greenland'), ('Grenada', 'Grenada'), ('Guadeloupe', 'Guadeloupe'), ('Guam', 'Guam'), ('Guatemala', 'Guatemala'), ('Guinea', 'Guinea'), ('Guinea-Bissau', 'Guinea-Bissau'), ('Guyana', 'Guyana'), ('Haiti', 'Haiti'), ('Heard\xa0&\xa0McDonald\xa0Islands', 'Heard\xa0&\xa0McDonald\xa0Islands'), ('Honduras', 'Honduras'), ('Hong\xa0Kong', 'Hong\xa0Kong'), ('Hungary', 'Hungary'), ('Iceland', 'Iceland'), ('India', 'India'), ('Indonesia', 'Indonesia'), ('Iraq', 'Iraq'), ('Ireland', 'Ireland'), ('Islamic\xa0Republic\xa0of\xa0Iran', 'Islamic\xa0Republic\xa0of\xa0Iran'), ('Israel', 'Israel'), ('Italy', 'Italy'), ('Ivory\xa0Coast', 'Ivory\xa0Coast'), ('Jamaica', 'Jamaica'), ('Japan', 'Japan'), ('Jordan', 'Jordan'), ('Kazakhstan', 'Kazakhstan'), ('Kenya', 'Kenya'), ('Kiribati', 'Kiribati'), ('Korea', 'Korea'), ('Kuwait', 'Kuwait'), ('Kyrgyzstan', 'Kyrgyzstan'), ('Lao\xa0People\xa0Democratic\xa0Republic', 'Lao\xa0People\xa0Democratic\xa0Republic'), ('Latvia', 'Latvia'), ('Lebanon', 'Lebanon'), ('Lesotho', 'Lesotho'), ('Liberia', 'Liberia'), ('Libyan\xa0Arab\xa0Jamahiriya', 'Libyan\xa0Arab\xa0Jamahiriya'), ('Liechtenstein', 'Liechtenstein'), ('Lithuania', 'Lithuania'), ('Luxembourg', 'Luxembourg'), ('Macau', 'Macau'), ('Madagascar', 'Madagascar'), ('Malawi', 'Malawi'), ('Malaysia', 'Malaysia'), ('Maldives', 'Maldives'), ('Mali', 'Mali'), ('Malta', 'Malta'), ('Marshall\xa0Islands', 'Marshall\xa0Islands'), ('Martinique', 'Martinique'), ('Mauritania', 'Mauritania'), ('Mauritius', 'Mauritius'), ('Mayotte', 'Mayotte'), ('Mexico', 'Mexico'), ('Micronesia', 'Micronesia'), ('Moldova', 'Moldova'), ('Monaco', 'Monaco'), ('Mongolia', 'Mongolia'), ('Monserrat', 'Monserrat'), ('Morocco', 'Morocco'), ('Mozambique', 'Mozambique'), ('Myanmar', 'Myanmar'), ('Namibia', 'Namibia'), ('Nauru', 'Nauru'), ('Nepal', 'Nepal'), ('Netherlands', 'Netherlands'), ('Netherlands\xa0Antilles', 'Netherlands\xa0Antilles'), ('New\xa0Caledonia', 'New\xa0Caledonia'), ('New\xa0Zealand', 'New\xa0Zealand'), ('Nicaragua', 'Nicaragua'), ('Niger', 'Niger'), ('Nigeria', 'Nigeria'), ('Niue', 'Niue'), ('Norfolk\xa0Island', 'Norfolk\xa0Island'), ('Northern\xa0Mariana\xa0Islands', 'Northern\xa0Mariana\xa0Islands'), ('Norway', 'Norway'), ('Oman', 'Oman'), ('Pakistan', 'Pakistan'), ('Palau', 'Palau'), ('Panama', 'Panama'), ('Papua\xa0New\xa0Guinea', 'Papua\xa0New\xa0Guinea'), ('Paraguay', 'Paraguay'), ('Peru', 'Peru'), ('Philippines', 'Philippines'), ('Pitcairn', 'Pitcairn'), ('Poland', 'Poland'), ('Portugal', 'Portugal'), ('Puerto\xa0Rico', 'Puerto\xa0Rico'), ('Qatar', 'Qatar'), ('Reunion', 'Reunion'), ('Romania', 'Romania'), ('Russian\xa0Federation', 'Russian\xa0Federation'), ('Rwanda', 'Rwanda'), ('Saint\xa0Lucia', 'Saint\xa0Lucia'), ('Samoa', 'Samoa'), ('San\xa0Marino', 'San\xa0Marino'), ('Sao\xa0Tome\xa0&\xa0Principe', 'Sao\xa0Tome\xa0&\xa0Principe'), ('Saudi\xa0Arabia', 'Saudi\xa0Arabia'), ('Senegal', 'Senegal'), ('Seychelles', 'Seychelles'), ('Sierra\xa0Leone', 'Sierra\xa0Leone'), ('Singapore', 'Singapore'), ('Slovakia', 'Slovakia'), ('Slovenia', 'Slovenia'), ('Solomon\xa0Islands', 'Solomon\xa0Islands'), ('Somalia', 'Somalia'), ('South\xa0Africa', 'South\xa0Africa'), ('South\xa0Georgia\xa0and\xa0the\xa0South\xa0Sandwich\xa0Islands', 'South\xa0Georgia\xa0and\xa0the\xa0South\xa0Sandwich\xa0Islands'), ('Spain', 'Spain'), ('Sri\xa0Lanka', 'Sri\xa0Lanka'), ('St.\xa0Helena', 'St.\xa0Helena'), ('St.\xa0Kitts\xa0and\xa0Nevis', 'St.\xa0Kitts\xa0and\xa0Nevis'), ('St.\xa0Pierre\xa0&\xa0Miquelon', 'St.\xa0Pierre\xa0&\xa0Miquelon'), ('St.\xa0Vincent\xa0&\xa0the\xa0Grenadines', 'St.\xa0Vincent\xa0&\xa0the\xa0Grenadines'), ('Sudan', 'Sudan'), ('Suriname', 'Suriname'), ('Svalbard\xa0&\xa0Jan\xa0Mayen\xa0Islands', 'Svalbard\xa0&\xa0Jan\xa0Mayen\xa0Islands'), ('Swaziland', 'Swaziland'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Syrian\xa0Arab\xa0Republic', 'Syrian\xa0Arab\xa0Republic'), ('Taiwan', 'Taiwan'), ('Tajikistan', 'Tajikistan'), ('Tanzania', 'Tanzania'), ('Thailand', 'Thailand'), ('Togo', 'Togo'), ('Tokelau', 'Tokelau'), ('Tonga', 'Tonga'), ('Trinidad\xa0&\xa0Tobago', 'Trinidad\xa0&\xa0Tobago'), ('Tunisia', 'Tunisia'), ('Turkey', 'Turkey'), ('Turkmenistan', 'Turkmenistan'), ('Turks\xa0&\xa0Caicos\xa0Islands', 'Turks\xa0&\xa0Caicos\xa0Islands'), ('Tuvalu', 'Tuvalu'), ('Uganda', 'Uganda'), ('Ukraine', 'Ukraine'), ('United\xa0Arab\xa0Emirates', 'United\xa0Arab\xa0Emirates'), ('United\xa0Kingdom\xa0\xa0Great\xa0Britain', 'United\xa0Kingdom\xa0\xa0Great\xa0Britain'), ('United\xa0States\xa0Minor\xa0Outlying\xa0Islands', 'United\xa0States\xa0Minor\xa0Outlying\xa0Islands'), ('United\xa0States\xa0Virgin\xa0Islands', 'United\xa0States\xa0Virgin\xa0Islands'), ('United\xa0States\xa0of\xa0America', 'United\xa0States\xa0of\xa0America'), ('Uruguay', 'Uruguay'), ('Uzbekistan', 'Uzbekistan'), ('Vanuatu', 'Vanuatu'), ('Vatican\xa0City\xa0State\xa0\xa0Holy\xa0See', 'Vatican\xa0City\xa0State\xa0\xa0Holy\xa0See'), ('Venezuela', 'Venezuela'), ('Viet\xa0Nam', 'Viet\xa0Nam'), ('Wallis\xa0&\xa0Futuna\xa0Islands', 'Wallis\xa0&\xa0Futuna\xa0Islands'), ('Western\xa0Sahara', 'Western\xa0Sahara'), ('Yemen', 'Yemen'), ('Yugoslavia', 'Yugoslavia'), ('Zaire', 'Zaire'), ('Zambia', 'Zambia'), ('Zimbabwe', 'Zimbabwe')], default='Colombia', max_length=100, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='acciones',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 11, 9, 16, 45, 48, 166382), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 11, 9, 16, 45, 48, 162381), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 11, 9, 16, 45, 48, 163381), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='graduated',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 11, 9, 16, 45, 48, 164381), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 11, 9, 16, 45, 48, 161381), max_length=50),
        ),
        migrations.AlterField(
            model_name='materias',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 11, 9, 16, 45, 48, 162381), max_length=50),
        ),
        migrations.AlterField(
            model_name='pensum',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 11, 9, 16, 45, 48, 161381), max_length=50),
        ),
        migrations.AlterField(
            model_name='periodos',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 11, 9, 16, 45, 48, 160381), max_length=50),
        ),
        migrations.AlterField(
            model_name='programas',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 11, 9, 16, 45, 48, 160381), max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 16, 45, 48, 160381)),
        ),
    ]
