# Generated by Django 4.2.7 on 2023-11-29 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0052_rename_homolacion_estudiante_homologacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciones',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 11, 29, 18, 2, 13, 59037), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 11, 29, 18, 2, 13, 41026), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cedulaAcudiente',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='document',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 11, 29, 18, 2, 13, 57025), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fotos',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='siet',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='simat',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='graduated',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 11, 29, 18, 2, 13, 59037), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 11, 29, 18, 2, 13, 41026), max_length=50),
        ),
        migrations.AlterField(
            model_name='materias',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 11, 29, 18, 2, 13, 57025), max_length=50),
        ),
        migrations.AlterField(
            model_name='pensum',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 11, 29, 18, 2, 13, 40026), max_length=50),
        ),
        migrations.AlterField(
            model_name='periodos',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 11, 29, 18, 2, 13, 39026), max_length=50),
        ),
        migrations.AlterField(
            model_name='programas',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 11, 29, 18, 2, 13, 40026), max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 18, 2, 13, 38026)),
        ),
    ]
