# Generated by Django 4.2.7 on 2023-11-29 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0053_alter_acciones_fecha_reg_alter_docente_fecha_reg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciones',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 11, 29, 19, 13, 57, 446407), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 11, 29, 19, 13, 57, 410233), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 11, 29, 19, 13, 57, 443369), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='graduated',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime(2023, 11, 29, 19, 13, 57, 445381), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 11, 29, 19, 13, 57, 407973), max_length=50),
        ),
        migrations.AlterField(
            model_name='materias',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 11, 29, 19, 13, 57, 441819), max_length=50),
        ),
        migrations.AlterField(
            model_name='pensum',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 11, 29, 19, 13, 57, 407002), max_length=50),
        ),
        migrations.AlterField(
            model_name='periodos',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 11, 29, 19, 13, 57, 406007), max_length=50),
        ),
        migrations.AlterField(
            model_name='programas',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 11, 29, 19, 13, 57, 407002), max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 19, 13, 57, 402996)),
        ),
    ]
