# Generated by Django 4.1 on 2023-01-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='end_time',
            field=models.DateField(verbose_name='Fecha_final'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='start_time',
            field=models.DateField(verbose_name='Fecha_inicio'),
        ),
    ]
