# Generated by Django 4.1 on 2023-01-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0003_facturas_monto_facturas_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='sub_codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
