# Generated by Django 4.1 on 2023-01-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0004_facturas_sub_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='consecutivo',
            field=models.PositiveIntegerField(default=0, verbose_name='Consecutivo'),
            preserve_default=False,
        ),
    ]
