# Generated by Django 4.1 on 2023-02-15 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0005_facturas_consecutivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturas',
            name='consecutivo',
        ),
        migrations.RemoveField(
            model_name='facturas',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='facturas',
            name='sub_codigo',
        ),
        migrations.CreateModel(
            name='FacturasSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(blank=True, max_length=400, null=True)),
                ('consecutivo', models.PositiveIntegerField()),
                ('pagado', models.DecimalField(decimal_places=0, default=0, max_digits=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facturas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financiero.facturas')),
            ],
        ),
    ]
