# Generated by Django 4.1 on 2023-08-03 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0008_gastos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturas',
            name='pagado',
        ),
    ]
