# Generated by Django 4.1 on 2023-11-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0009_remove_facturas_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='monto',
            field=models.DecimalField(decimal_places=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='facturassub',
            name='pagado',
            field=models.DecimalField(decimal_places=0, max_digits=100),
        ),
    ]
