# Generated by Django 4.1 on 2023-11-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0010_alter_facturas_monto_alter_facturassub_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturassub',
            name='observacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
